services:
  postgres:
    image: postgres:15-alpine
    container_name: assistant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: assistant
      POSTGRES_USER: assistant
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assistant -d assistant"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - assistant-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: assistant-chromadb
    restart: unless-stopped
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "perl", "-e", "use IO::Socket::INET; exit(1) unless IO::Socket::INET->new(PeerAddr=>'localhost:8000',Timeout=>5)"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - assistant-network

  assistant:
    build:
      context: .
      tags:
        - assistant-api:latest
    image: assistant-api:latest
    container_name: assistant-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://assistant:${POSTGRES_PASSWORD}@postgres:5432/assistant
      - CHROMADB_URL=http://chromadb:8000
      - OLLAMA_URL=http://host.docker.internal:11434
      - SIGNAL_PHONE_NUMBER=${SIGNAL_PHONE_NUMBER}
      - NOTION_TOKEN=${NOTION_TOKEN}
    volumes:
      - ./src:/app/src  # Development only - remove in production
      - ./logs:/app/logs
      - signal_cli_data:/root/.local/share/signal-cli
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - assistant-network

volumes:
  postgres_data:
  chroma_data:
  signal_cli_data:

networks:
  assistant-network:
    driver: bridge